---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: sa-webapp
spec:
  replicas: 3 
  minReadySeconds: 15
  selector:
    matchLabels: 
      app: sa-webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-webapp
    spec:
      containers:
        - image: sajalsood/sa-webapp:v4
          imagePullPolicy: Always
          name: sa-webapp
          env:
            - name: SA_LOGIC_API_URL
              value: "http://sa-logic"
          ports:
            - containerPort: 8080